import type { CaseStudy } from "@/types/content";

/**
 * Case studies — each record is CMS-ready: required fields below match the
 * CaseStudy schema in @/types/content. Optional fields (summary, gallery,
 * status, sourceUrl) can be filled in via a future admin panel.
 *
 * - `status`: omit or set "published" to show on site; "draft" hides it.
 * - `summary`: short tagline for cards. Falls back to `result` if absent.
 * - `time` / `location`: "待确认" inputs render as "持续 · Ongoing" / "中国 · 多基地".
 */
export const caseStudies: CaseStudy[] = [
  {
    slug: "xinjiang-shihezi-cotton",
    title: "T280 新疆石河子棉花植保",
    titleEn: "T280 · Xinjiang Shihezi cotton protection",
    summary: "新疆棉田连续一个月作业 · 120kg 载重",
    summaryEn: "Month-long Xinjiang cotton ops · 120 kg payload",
    productModels: ["T280"],
    scenario: "agriculture-plant-protection",
    location: "新疆石河子",
    locationEn: "Shihezi, Xinjiang",
    time: "2025 年 7 月",
    timeEn: "July 2025",
    task: "为期一个月棉花打药服务，面向大面积棉田作业。",
    taskEn: "A month-long cotton-protection programme over large-scale fields.",
    result: "以 120kg 载重能力稳定支撑大面积棉花植保任务，连续一个月作业未出现非计划中断。",
    resultEn: "Sustained 120 kg payload supported large-area cotton protection with no unscheduled interruption over the full month.",
    keyData: [{ label: "载重", value: "120", unit: "kg" }],
    media: ["case-xinjiang-cotton-cover"],
    sourceUrl: "https://www.shitianuav.com/case/110.html",
    status: "published",
    showOnHomepage: true,
    priority: "P0"
  },
  {
    slug: "longkou-golf-maintenance",
    title: "T280 龙口南山高尔夫植保",
    titleEn: "T280 · Longkou Nanshan Golf maintenance",
    summary: "3 小时完成 18 洞作业 · 农药成本降低约 30%",
    summaryEn: "18 holes in 3 hours · ~30% lower chemical cost",
    productModels: ["T280", "HIZONE"],
    scenario: "golf-maintenance",
    location: "山东龙口南山高尔夫",
    locationEn: "Nanshan Golf, Longkou, Shandong",
    time: "2025 年 5 月 29 日",
    timeEn: "29 May 2025",
    task: "为南山高尔夫球场草坪执行精准植保养护，覆盖球道与果岭。",
    taskEn: "Precision turf protection across the fairways and greens of Nanshan Golf.",
    result: "T280 配合 HIZONE 处方图，3 小时完成 18 洞作业，农药成本较人工方案降低约 30%。",
    resultEn: "T280 paired with HIZONE prescription maps covered 18 holes in 3 hours, cutting chemical cost by roughly 30% versus manual work.",
    keyData: [
      { label: "作业范围", value: "18", unit: "洞" },
      { label: "作业时间", value: "3", unit: "小时" },
      { label: "农药成本降低", value: "约 30%" }
    ],
    media: ["hizone-gallery-03"],
    sourceUrl: "https://www.shitianuav.com/case/109.html",
    status: "published",
    showOnHomepage: true,
    priority: "P0"
  },
  {
    slug: "weihai-apple-pollination",
    title: "T280 威海苹果园授粉",
    titleEn: "T280 · Weihai apple orchard pollination",
    summary: "12 分钟完成 50 亩授粉 · 预计产量提升 15-20%",
    summaryEn: "50 mu pollinated in 12 minutes · projected 15–20% yield uplift",
    productModels: ["T280"],
    scenario: "orchard-pollination",
    location: "山东威海环翠区",
    locationEn: "Huancui, Weihai, Shandong",
    time: "2025 年 4 月 26 日",
    timeEn: "26 April 2025",
    task: "在花期窗口内，执行苹果园低空授粉作业。",
    taskEn: "Low-altitude apple-orchard pollination during the blossom window.",
    result: "12 分钟完成 50 亩授粉，长期成本预估降低 30%-50%，预计产量提升 15%-20%。",
    resultEn: "Pollinated 50 mu in 12 minutes; long-term cost projected 30–50% lower, with an expected 15–20% yield uplift.",
    keyData: [
      { label: "作业面积", value: "50", unit: "亩" },
      { label: "作业时间", value: "12", unit: "分钟" },
      { label: "长期成本降低", value: "30%-50%" },
      { label: "预计产量提升", value: "15%-20%" }
    ],
    media: ["case-apple-pollination-cover"],
    sourceUrl: "https://www.shitianuav.com/case/108.html",
    status: "published",
    showOnHomepage: true,
    priority: "P0"
  },
  {
    slug: "laiyang-pear-frost",
    title: "T280 莱阳梨基地防霜冻",
    titleEn: "T280 · Laiyang pear-orchard frost defence",
    summary: "凌晨 1-5 点持续作业 · 强下洗风场协同篝火",
    summaryEn: "Continuous 01:00–05:00 ops · downwash paired with ground bonfires",
    productModels: ["T280"],
    scenario: "frost-protection",
    location: "山东莱阳梨基地",
    locationEn: "Laiyang pear orchard, Shandong",
    time: "2025 年 4 月 15 日凌晨",
    timeEn: "Pre-dawn, 15 April 2025",
    task: "在低温时段配合地面篝火形成温热气流对流，执行夜间防霜冻作业。",
    taskEn: "Overnight frost-defence operations pairing downwash with ground bonfires to create warm-air convection.",
    result: "T280 强下洗风场打破冷气层与暖气层的稳定结构，支撑果园低温风险防护任务。",
    resultEn: "T280 downwash broke the stable cold-warm air stratification, supporting the orchard's low-temperature risk defence.",
    keyData: [{ label: "作业时段", value: "凌晨 1 点至 5 点" }],
    media: ["t280-gallery-03"],
    sourceUrl: "https://www.shitianuav.com/case/107.html",
    status: "published",
    priority: "P0"
  },
  {
    slug: "qingdao-red-cross-pump",
    title: "T280 吊运水泵助力青岛红十字搜救队演练",
    summary: "60kg 水泵 10 分钟从山下吊运至山上",
    productModels: ["T280"],
    scenario: "emergency-lift",
    location: "山东青岛",
    time: "2025 年",
    task: "为山地救援演练吊运三级抽水泵与配套物资。",
    result: "60kg 水泵 10 分钟从山下运至山上，验证常规运输受限场景下的应急吊运能力。",
    keyData: [
      { label: "吊运重量", value: "60", unit: "kg" },
      { label: "运输时间", value: "10", unit: "分钟" }
    ],
    media: ["case-rescue-pump-cover"],
    sourceUrl: "https://www.shitianuav.com/case/106.html",
    status: "published",
    priority: "P0"
  },
  {
    slug: "huangdao-maritime-lift",
    title: "T280 黄岛海上 15 公里吊运",
    summary: "海上点对点 15 公里吊运 · 近岸应急物流",
    productModels: ["T280"],
    scenario: "maritime-logistics",
    location: "山东青岛黄岛海域",
    time: "2025 年",
    task: "在黄岛海域执行海上点对点货物吊运任务。",
    result: "验证 T280 在 15 公里海上点对点航程下的低空物流与应急物资投送能力。",
    keyData: [{ label: "海上吊运距离", value: "15", unit: "km" }],
    media: ["t280-gallery-06"],
    sourceUrl: "https://www.shitianuav.com/news/",
    status: "published",
    priority: "P0"
  },
  {
    slug: "orchard-low-carbon-demo",
    title: "农业部 5000 亩果园环保低碳示范基地项目",
    summary: "5000 亩示范基地 · 农药 -25% · 人工 -50%",
    productModels: ["S270", "T280", "HIZONE"],
    scenario: "agriculture-plant-protection",
    location: "国内多省",
    time: "2022 年",
    task: "承担农业部 5000 亩果园环保低碳示范基地项目的低空作业组合。",
    result: "农药使用率降低 ≥25%，人工成本减少 ≥50%，机械使用率提高 ≥60%。",
    keyData: [
      { label: "项目面积", value: "5000", unit: "亩" },
      { label: "农药使用率降低", value: "≥25%" },
      { label: "人工成本减少", value: "≥50%" },
      { label: "机械使用率提高", value: "≥60%" }
    ],
    media: ["s270-gallery-04"],
    sourceUrl: "https://www.shitianuav.com/news/445.html",
    status: "published",
    priority: "P0"
  },
  {
    slug: "s270-pine-wilt-control",
    title: "S270 防治松材线虫病",
    summary: "无人机低量喷雾 · 连续三年政府认可",
    productModels: ["S270"],
    scenario: "forestry-protection",
    location: "国内多省山林",
    time: "持续",
    task: "以无人机超低量喷雾结合地面喷雾补防，执行松材线虫病防治。",
    result: "防治效果连续三年获得政府认可，成为林业防护的常态化作业方案。",
    keyData: [{ label: "政府认可周期", value: "连续三年" }],
    media: ["s270-gallery-02"],
    sourceUrl: "https://www.shitianuav.com/case/102.html",
    status: "published",
    priority: "P0"
  },
  {
    slug: "s270-defoliant-seven-days",
    title: "S270 喷洒脱叶剂 7 天效果对比",
    summary: "棉田脱叶剂喷洒 · 7 天效果对比",
    productModels: ["S270"],
    scenario: "agriculture-plant-protection",
    location: "新疆棉田",
    time: "持续",
    task: "在棉田执行脱叶剂喷洒作业，作业前后建立 7 天效果对比记录。",
    result: "以可量化的对比数据，验证 S270 在大田植保作业链中的稳定输出。",
    keyData: [{ label: "效果观察周期", value: "7", unit: "天" }],
    media: ["s270-gallery-03"],
    sourceUrl: "https://www.shitianuav.com/case/105.html",
    status: "published",
    priority: "P1"
  },
  {
    slug: "s270-akesu-operation",
    title: "S270 新疆阿克苏地区作业",
    summary: "阿克苏地区大田植保作业",
    productModels: ["S270"],
    scenario: "agriculture-plant-protection",
    location: "新疆阿克苏地区",
    time: "持续",
    task: "在阿克苏地区执行大田植保作业。",
    result: "与石河子棉田案例形成西北大田作业的连续证据。",
    keyData: [],
    media: ["s270-gallery-05"],
    sourceUrl: "https://www.shitianuav.com/case/104.html",
    status: "published",
    priority: "P1"
  },
  {
    slug: "forest-fire-drill",
    title: "兴安盟五叉沟森林防火演练",
    summary: "森林防火演练 · 空地协同",
    productModels: ["H15", "T280"],
    scenario: "forestry-protection",
    location: "内蒙古兴安盟五叉沟",
    time: "持续",
    task: "参与五叉沟森林防火演练，配合地面消防力量执行巡查与协同。",
    result: "为山林防护与应急协同场景提供作业证据。",
    keyData: [],
    media: ["h15-gallery-06"],
    sourceUrl: "https://www.shitianuav.com/news/",
    status: "published",
    priority: "P1"
  }
];
